<html>

<head></head>

<body>
  <h3><?= $this->title; ?></h3>

  <form action="/login/register" method="post">
    Name: <input type="text" value="" name="name" /><br />
    Email: <input type="text" value="" name="email" /><br />
    Password: <input type="password" value="" name="password" /><br />
    Confirm Password: <input type="password" value="" name="passwordConfirm" /><br />
    <input type="submit" value="Register"><br />
  </form>
</body>

</html>
