<html>

<head></head>

<body>
  <h3><?= $this->title; ?></h3>

  <?php
  /** @var \App\Model\User $user */
  $user = $this->user;
  ?>

  <? if(!$user): ?>
  <h3>Login</h3>
  <form action="/login/auth" method="post">
    <div>Email:</div> <input type="text" value="" name="email"><br>
    <div>Password:</div> <input type="password" value="" name="password"><br>
    <input type="submit" value="Login">
  </form>

  <h3>Registration</h3>
  <form action="/login/register" method="post">
    <div>Name:</div> <input type="text" value="" name="name" /><br />
    <div> Email:</div> <input type="text" value="" name="email" /><br />
    <div>Password:</div> <input type="password" value="" name="password" /><br />
    <div>Confirm Password:</div> <input type="password" value="" name="passwordConfirm" /><br />
    <input type="submit" value="Register"><br />
  </form>
  <? endif; ?>


</body>

</html>
